development: &local

  site_name:        'MissPapitas'
  site_language:    'en' # 'es'

  template_name:    default

  # twitter_oauth_token:    ENTER-YOUR-TOKEN-HERE
  # twitter_oauth_secret:   ENTER-YOUR-TOKEN-SECRET-HERE

  twitter_account_name:   misspapitas
  twitter_account_pass:   password

  # db_type:        sqlite
  #   db_connection:  sqlite3:///ROOT/papitas_dev.db

production:
  <<: *local

  # db_type:          mysql
  # db_connection:    mysql://root:*****@localhost/papitas_prod
  # db_type:          sqlite
  # db_connection:    sqlite3:///ROOT/papitas_prod.db


staging:
  <<: *local

  # db_type:        sqlite
  #   db_connection:  sqlite3:///ROOT/papitas_stage.db

test:
  <<: *local

  # db_type:        sqlite
  #   db_connection:  sqlite3:///ROOT/papitas_test.db