development: &local

  site_name:              'MissPirata'
  site_language:          'en' # 'es'

  template_name:          default
  enable_memcache:        false


  # Options
  reqiure_oath_login:     false   # Require users to have a twitter account to sign up.
  tweet_per_session:      false   # Should user only be able to tweet once per session, or multiple times (could be a spam problem).
  send_though_sender:     true    # Sender also sends out tweet. (Requires require_oauth_login to be true.)
  auth_token_hash:        ABCDE123

  view_account_stream:    true  # Fetch the account timeline stream for display purposes. (Highly recommend caching on this!) (Requires require_oauth_login to be true.)


  # If require_oauth_login == true, enter the OAuth app key/secret here
  twitter_oauth_token:    ENTER-YOUR-TOKEN-HERE
  twitter_oauth_secret:   ENTER-YOUR-TOKEN-SECRET-HERE

  # Recipient Twitter account
  twitter_account_name:   misspirata
  twitter_account_pass:   password

  db_type:        sqlite
  db_connection:  sqlite3:///ROOT/pirata_dev.db

production:
  <<: *local

  # db_type:          mysql
  # db_connection:    mysql://root:*****@localhost/pirata_prod
  db_type:          sqlite
  db_connection:    sqlite3:///ROOT/pirata_prod.db


staging:
  <<: *local

  db_type:        sqlite
  db_connection:  sqlite3:///ROOT/pirata_stage.db

test:
  <<: *local

  db_type:        sqlite
  db_connection:  sqlite3:///ROOT/pirata_test.db